### ISSUE TITLE
缺失部分歌曲数据

### ISSUE THREAD

**Issue by yuangezhizao** [CrazyKidCN/maimaiDX-CN-songs-database#2]
1. 情况一：同时有`标准铺面`和`DX 铺面`的歌曲，缺少标准铺面，举例 RT
![image](https://user-images.githubusercontent.com/16861681/127764005-48c1490b-49dc-4419-8142-7e514837ce01.png)

2. 情况二：目前唯一的特例，同名铺面`Link`有两个分类对应两首歌。。。
![image](https://user-images.githubusercontent.com/16861681/127764102-19d80f35-785f-40c2-97fa-59198d4e0cad.png)

**Comment by CrazyKidCN** [comment]
情况已收到，我会尝试在本次更新中补录这些数据，感谢您的反馈

**Comment by CrazyKidCN** [comment]
情况1 我看了下，好像没有问题。。。
```json
{
    "title": "君の知らない物語",
    "artist": "supercell「化物語」",
    "category": "流行&动漫",
    "image_file": "f1fbe1553464d234.png",
    "lev_bas": "3",
    "lev_adv": "6",
    "lev_exp": "8",
    "lev_mas": "11",
    "dx_lev_bas": "3",
    "dx_lev_adv": "6",
    "dx_lev_exp": "8",
    "dx_lev_mas": "12",
    "version": "舞萌DX 2021"
  },
  {
    "title": "コネクト",
    "artist": "ClariS　「魔法少女まどか☆マギカ」",
    "category": "流行&动漫",
    "image_file": "30bc38a09670248e.png",
    "lev_bas": "5",
    "lev_adv": "7",
    "lev_exp": "8",
    "lev_mas": "11+",
    "dx_lev_bas": "3",
    "dx_lev_adv": "6",
    "dx_lev_exp": "8+",
    "dx_lev_mas": "11",
    "dx_lev_remas": "12+",
    "version": "舞萌DX 2021"
  },
```

**Comment by yuangezhizao** [comment]
> 情况1 我看了下，好像没有问题。。。
> 
> ```json
> {
>     "title": "君の知らない物語",
>     "artist": "supercell「化物語」",
>     "category": "流行&动漫",
>     "image_file": "f1fbe1553464d234.png",
>     "lev_bas": "3",
>     "lev_adv": "6",
>     "lev_exp": "8",
>     "lev_mas": "11",
>     "dx_lev_bas": "3",
>     "dx_lev_adv": "6",
>     "dx_lev_exp": "8",
>     "dx_lev_mas": "12",
>     "version": "舞萌DX 2021"
>   },
>   {
>     "title": "コネクト",
>     "artist": "ClariS　「魔法少女まどか☆マギカ」",
>     "category": "流行&动漫",
>     "image_file": "30bc38a09670248e.png",
>     "lev_bas": "5",
>     "lev_adv": "7",
>     "lev_exp": "8",
>     "lev_mas": "11+",
>     "dx_lev_bas": "3",
>     "dx_lev_adv": "6",
>     "dx_lev_exp": "8+",
>     "dx_lev_mas": "11",
>     "dx_lev_remas": "12+",
>     "version": "舞萌DX 2021"
>   },
> ```

原来两个铺面的等级是放到一起了，我看漏了……情况 1 应该不存在了
