### ISSUE TITLE
部分乐曲数据有误

### ISSUE THREAD

**Issue by zetaraku** [CrazyKidCN/maimaiDX-CN-songs-database#3]
https://github.com/CrazyKidCN/maimaiDX-CN-songs-database/blob/a3065fcdf23689a7bfa03d9a61aa1aef67bbc15c/maidata.json#L3132-L3146

乐曲 BATTLE NO.1 并不存在标准谱面

https://github.com/CrazyKidCN/maimaiDX-CN-songs-database/blob/a3065fcdf23689a7bfa03d9a61aa1aef67bbc15c/maidata.json#L5526-L5536

日版官方的乐曲名为

```
D✪N’T  ST✪P  R✪CKIN’
```

而非

```
D✪N’T ST✪P R✪CKIN’
```

**Comment by CrazyKidCN** [comment]
> https://github.com/CrazyKidCN/maimaiDX-CN-songs-database/blob/a3065fcdf23689a7bfa03d9a61aa1aef67bbc15c/maidata.json#L3132-L3146
> 
> 乐曲 BATTLE NO.1 并不存在标准谱面
> 
> https://github.com/CrazyKidCN/maimaiDX-CN-songs-database/blob/a3065fcdf23689a7bfa03d9a61aa1aef67bbc15c/maidata.json#L5526-L5536
> 
> 日版官方的乐曲名为
> 
> ```
> D✪N’T  ST✪P  R✪CKIN’
> ```
> 
> 而非
> 
> ```
> D✪N’T ST✪P R✪CKIN’
> ```

感谢您的反馈, batter no.1 应该是以前程序没写好造成的

而 dont stop rockin 我去国服微信 maimai-net 检查了一下, 发现确实是只有一个空格的, 因为歌曲数据是从国服maimai-net爬的, 以国服 maimai-net 为准

**Comment by zetaraku** [comment]
我之前在爬国际板歌单时也遇过相同情形，所以觉得可能哪边出错了
cheerio 的 .text() 或 DOM 的 .innerText 在抓取内容时，多个空格会被合并成一个
网页在渲染时也会合并空格，我想可能是造成看不出实际上有两个空格的原因
